# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowBuild.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

def click():
    print("Clicked")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        self.Create_Game = QtWidgets.QPushButton(self.centralwidget)
        self.Create_Game.setGeometry(QtCore.QRect(72, 20, 121, 32))
        self.Create_Game.setObjectName("Create_Game")
        self.Create_Game.clicked.connect(click)

        self.Clear_Game = QtWidgets.QPushButton(self.centralwidget)
        self.Clear_Game.setGeometry(QtCore.QRect(190, 20, 113, 32))
        self.Clear_Game.setObjectName("Clear_Game")
        self.Clear_Game.clicked.connect(click)

        self.Eliminate_Player = QtWidgets.QPushButton(self.centralwidget)
        self.Eliminate_Player.setGeometry(QtCore.QRect(80, 70, 151, 32))
        self.Eliminate_Player.setObjectName("Eliminate_Player")
        self.Eliminate_Player.clicked.connect(click)

        self.Remove_Player = QtWidgets.QPushButton(self.centralwidget)
        self.Remove_Player.setGeometry(QtCore.QRect(570, 20, 113, 32))
        self.Remove_Player.setObjectName("Remove_Player")
        self.Remove_Player.clicked.connect(click)

        self.Player_list_box1 = QtWidgets.QComboBox(self.centralwidget)
        self.Player_list_box1.setGeometry(QtCore.QRect(90, 110, 104, 26))
        self.Player_list_box1.setObjectName("Player_list_box1")


        self.Player_list_box2 = QtWidgets.QComboBox(self.centralwidget)
        self.Player_list_box2.setGeometry(QtCore.QRect(580, 70, 104, 26))
        self.Player_list_box2.setObjectName("Player_list_box2")


        self.View_Game = QtWidgets.QPushButton(self.centralwidget)
        self.View_Game.setGeometry(QtCore.QRect(110, 190, 113, 32))
        self.View_Game.setObjectName("View_Game")
        self.View_Game.clicked.connect(click)

        self.Email_Assignments = QtWidgets.QPushButton(self.centralwidget)
        self.Email_Assignments.setGeometry(QtCore.QRect(400, 180, 151, 32))
        self.Email_Assignments.setObjectName("Email_Assignments")
        self.Email_Assignments.clicked.connect(click)

        self.Display_Game_Box = QtWidgets.QTextBrowser(self.centralwidget)
        self.Display_Game_Box.setGeometry(QtCore.QRect(60, 240, 256, 241))
        self.Display_Game_Box.setObjectName("Display_Game_Box")


        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Create_Game.setText(_translate("MainWindow", "Create Game"))
        self.Clear_Game.setText(_translate("MainWindow", "Clear Game"))
        self.Eliminate_Player.setText(_translate("MainWindow", "Eliminate Player"))
        self.Remove_Player.setText(_translate("MainWindow", "Remove Player"))
        self.View_Game.setText(_translate("MainWindow", "View Game"))
        self.Email_Assignments.setText(_translate("MainWindow", "Email Assignments"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
