# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowBuild.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import json

from PyQt5 import QtCore, QtWidgets
import sys
from RunGame import Controller

"""
Builds GUI
"""
class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #eliminate player combo box
        self.EliminatePlayerComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.EliminatePlayerComboBox.setGeometry(QtCore.QRect(30, 180, 151, 41))
        self.EliminatePlayerComboBox.setObjectName("EliminatePlayerComboBox")

        #remove player combo box
        self.RemovePlayerComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.RemovePlayerComboBox.setGeometry(QtCore.QRect(30, 390, 151, 41))
        self.RemovePlayerComboBox.setObjectName("RemovePlayerComboBox")

        #eliminate player button
        self.Eliminate_Player = QtWidgets.QPushButton(self.centralwidget)
        self.Eliminate_Player.setGeometry(QtCore.QRect(30, 140, 151, 25))
        self.Eliminate_Player.setObjectName("Eliminate_Player")
        self.Eliminate_Player.clicked.connect(lambda: Controller.eliminatePlayer(str(self.EliminatePlayerComboBox.currentText())))

        #remove player button
        self.Remove_Player = QtWidgets.QPushButton(self.centralwidget)
        self.Remove_Player.setGeometry(QtCore.QRect(30, 350, 151, 25))
        self.Remove_Player.setObjectName("Remove_Player")
        self.Remove_Player.clicked.connect(lambda: Controller.removePlayer(str(self.RemovePlayerComboBox.currentText())))

        #display game text box
        self.Display_Game_Box = QtWidgets.QTextBrowser(self.centralwidget)
        self.Display_Game_Box.setGeometry(QtCore.QRect(210, 60, 571, 501))
        self.Display_Game_Box.setObjectName("Display_Game_Box")

        #view game button
        self.View_Game = QtWidgets.QPushButton(self.centralwidget)
        self.View_Game.setGeometry(QtCore.QRect(210, 10, 571, 25))
        self.View_Game.setObjectName("View_Game")
        self.View_Game.clicked.connect(lambda: self.Display_Game_Box.append(Controller.displayGame()))

        #email assignments button
        self.Email_Assignments = QtWidgets.QPushButton(self.centralwidget)
        self.Email_Assignments.setGeometry(QtCore.QRect(20, 10, 171, 25))
        self.Email_Assignments.setObjectName("Email_Assignments")
        self.Email_Assignments.clicked.connect(lambda: Controller.emailInitialAssignments())

        #update combo boxes button
        self.Update_Combo_Boxes = QtWidgets.QPushButton(self.centralwidget)
        self.Update_Combo_Boxes.setGeometry(QtCore.QRect(20, 40, 171, 25))
        self.Update_Combo_Boxes.setObjectName("Update Combo Boxes")
        self.Update_Combo_Boxes.clicked.connect(lambda: Controller.updateComboBoxes(self.EliminatePlayerComboBox, self.RemovePlayerComboBox))

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Eliminate_Player.setText(_translate("MainWindow", "Eliminate Player"))
        self.Remove_Player.setText(_translate("MainWindow", "Remove Player"))
        self.View_Game.setText(_translate("MainWindow", "View Game"))
        self.Email_Assignments.setText(_translate("MainWindow", "Email Assignments"))
        self.Update_Combo_Boxes.setText(_translate("MainWindow", "Update Combo Boxes"))


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
